config/routes.rb
Rails.application.routes.draw do
  resources :events

  resources :locations do
    resources :events
  end

  resources :participants do
    resources :events
  end

  resources :locations do
    resources :events, only: :index
  end

  resources :events do
    resources :participants, only: :index
  end


  get 'welcome/home'
  root 'welcome#home'

  get '/signin' => "sessions#signin"
  post '/signin' => 'sessions#signin_post', as: "signin_post"
  get '/signup' => 'sessions#signup'
  post '/signup' => 'sessions#signup_post', as: "signup_post"
  delete "/signout" => 'sessions#signout'

  get '/auth/facebook/callback' => 'sessions#facebook'
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  has_many :event_participants
  has_many :events, through: :event_participants
  has_many :locations, through: :events

  validates :nickname, presence: true
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :redirect_if_not_signed_in
  before_action :create_participant, only: [:new]
  before_action :set_participant, only: [:show, :edit, :update, :destroy]
  before_action :set_event, only: [:index, :show]


  def index
    @participants = Participant.by_user(current_user)

    if request.xhr? != 0
      render "index"
    else
      render json: @event.participants if @event
    end
  end

  def create
    @participant = current_user.participants.build(participant_params)

    if @participant.save
      redirect_to participants_path, notice: "Participant was created successfully"
    else
      render :new
    end
  end

  def show
    set_previous_participant(@participant)
    set_next_participant(@participant)
    set_participant_indexes(@participant)
    if request.xhr? != 0
      render "show"
    else
      render json: @participant
    end
  end

  def update
    if @participant.update(participant_params)
      redirect_to participant_path(@participant), notice: "Participant was updated successfully"
    else
      render :edit
    end
  end

  def destroy
    @participant.destroy
    redirect_to participants_path, notice: "Participant was deleted successfully"
  end

  private
    def set_previous_participant(participant)
      @previous = Participant.previous(participant)
    end

    def set_next_participant(participant)
      @next = Participant.next(participant)
    end

    def set_participant_indexes(participant)
      @indexes = Participant.indexes(participant)
    end

    def create_participant
      @participant = current_user.participants.build
    end

    def set_participant
      @participant = Participant.by_user(current_user).find(params[:id])
    end

    def participant_params
      params.require(:participant).permit(:nickname, :first_name, :last_name, :email, :phone_number)
    end

    def set_event
      @event = Event.by_user(current_user).find(params[:event_id]) if params[:event_id]
    end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
  def participant_to_s(participant)
    full_name = "#{participant.first_name} #{participant.last_name}"
    full_name == " " ? "#{participant.nickname}" : full_name + "(#{participant.nickname})"
  end

end

app/views/participants/_form.html.erb
<%= render "layouts/form_errors", object: participant %>

<%= form_for participant do |f| %>
  <fieldset class="participant_fieldset">
    <h3>Participant Details</h3>
    <div>
      <%= f.label :nickname, "Nickname"%><br>
      <%= f.text_field :nickname, class: "shadow" %>
    </div>
    <br>

    <div>
      <%= f.label :first_name, "First Name"%><br>
      <%= f.text_field :first_name, class: "shadow" %>
    </div>
    <br>
  
    <div>
      <%= f.label :last_name, "Last Name"%><br>
      <%= f.text_field :last_name, class: "shadow" %>
    </div>
    <br>

    <div>
      <%= f.label :email, "Email"%><br>
      <%= f.email_field :email, class: "shadow" %>
    </div>
    <br>

    <div>
      <%= f.label :phone_number, "Phone Number"%><br>
      <%= f.telephone_field :phone_number, class: "shadow" %>
    </div>
    <br>

    <div>
      <%= f.submit %>
    </div>
  </fieldset>
<% end %>

app/views/participants/_participants.html.erb
<table class="participant_table">
  <tr>
    <th>Nickname</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Phone Number</th>
    <th>Events</th>
  </tr>
  <% participants.each do |participant| %>
    <tr>
      <td><%= link_to participant.nickname, participant_path(participant) %></td>
      <td><%= participant.first_name %></td>
      <td><%= participant.last_name %></td>
      <td><%= participant.email %></td>
      <td><%= participant.phone_number %></td>
      <td><%= link_to participant.events.count, participant_events_path(participant) %>
    </tr>
  <% end %>
</table>

app/views/participants/edit.html.erb
<div class="edit_participant">
  <h1>Edit <%= @participant.nickname %></h1>
  <%= render 'form', participant: @participant %>
</div>

app/views/participants/index.html.erb
<div class="participants_index">
  <h1>Participants</h1>
  <p><%= link_to "+ New Participant", new_participant_path, class: "add_participant shadow" %></p>

  <% if !@participants.empty? %>
    <%= render "participants", participants: @participants %>
  <% end %>  
</div>

app/views/participants/new.html.erb
<div class="new_participant">
  <h1>Create A New Participant</h1>
  <%= render 'form', participant: @participant %>
</div>

app/views/participants/show.html.erb
<h1 id="main_head">Participant Details -
  <%= link_to "edit", edit_participant_path(@participant) %> |
  <%= link_to "delete", participant_path(@participant), method: :delete, data: { confirm: "Are you sure?"} %>
</h1>

<div class="participant_details shadow">
  <%= link_to "<", participant_path(@previous), class: "load_previous_participant", data: {indexes: @indexes, current: @participant.id} %>
  <%= link_to ">", participant_path(@next), class: "load_next_participant", data: {indexes: @indexes, current: @participant.id} %>

  <h3 id="nickname">Nickname: <%= @participant.nickname %></h3>
  <h3 id="first_name">First Name: <%= @participant.first_name %></h3>
  <h3 id="last_name">Last Name: <%= @participant.last_name %></h3>
  <h3 id="email">Email: <%= @participant.email %></h3>
  <h3 id="phone_number">Phone Number: <%= @participant.phone_number %></h3>
</div>

<div class="participant_events">
  <% if @participant.events.any? %>
    <h1>Events</h1>
    <%= link_to "Load Events", participant_events_path(@participant), class: "load_participant_events" %>
    <div class="events"> 
    </div>
  <% else %>
    <h1>No events for this participant</h1>
  <% end %>
</div>