config/routes.rb
Rails.application.routes.draw do
  resources :events

  resources :locations do
    resources :events
  end

  resources :participants do
    resources :events
  end

  resources :locations do
    resources :events, only: :index
  end

  resources :events do
    resources :participants, only: :index
  end


  get 'welcome/home'
  root 'welcome#home'

  get '/signin' => "sessions#signin"
  post '/signin' => 'sessions#signin_post', as: "signin_post"
  get '/signup' => 'sessions#signup'
  post '/signup' => 'sessions#signup_post', as: "signup_post"
  delete "/signout" => 'sessions#signout'

  get '/auth/facebook/callback' => 'sessions#facebook'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :location
  has_many :event_participants
  has_many :participants, through: :event_participants

  validates :name, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validate :valid_time?

  def location_attributes=(attributes)
    self.location = Location.by_user(self.user).find_or_create_by(name: attributes[:name]) if attributes[:name] != ""
  end

  def participants_attributes=(attributes)
    attributes.values.each do |attributes|
      self.participants << Participant.by_user(self.user).find_or_create_by(nickname: attributes[:nickname]) if attributes[:nickname] != ""
    end
  end

  def start_time=(attribute)
    write_attribute(:start_time, attribute.to_time.to_datetime)
  end

  def end_time=(attribute)
    write_attribute(:end_time, attribute.to_time.to_datetime)
  end

  # class scope methods
  

  def self.old_events
    where("start_time < ?", DateTime.now)
  end

  def self.starts_today
    self.starts_now_til_days(0)
  end

  def self.starts_now_til_days(days)
    where("start_time >= ? AND start_time <= ?", DateTime.now.beginning_of_day, (DateTime.now + days).end_of_day)
  end

  def self.upcoming_events
    where("start_time >= ?", DateTime.now)
  end

  def self.happening_now
    where("start_time <= ? AND end_time >= ?", DateTime.now, DateTime.now)
  end

  # validation code below
  def valid_time?
    return if !self.user || !self.location || !self.start_time || !self.end_time

    errors.add(:start_time, "can't be between another event's start and end time at the same location") if intersects_another_event?(self.start_time)
    errors.add(:end_time, "can't be between another event's start and end time at the same location") if intersects_another_event?(self.end_time)
    errors.add(:end_time, "can't be before the start time") if end_time < start_time
    errors.add(:start_time, "can't be before today") if start_time < Time.zone.today.beginning_of_day.to_datetime
  end

  private

    def intersects_another_event?(time)
      self.user.events.any? do |event|
        if self.location == event.location && event != self
          if event.start_time < time && time < event.end_time
            true
          end
        end
      end
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :redirect_if_not_signed_in
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :create_event, only: [:new]
  before_action :set_location, except: [:destroy]
  before_action :set_participant, only: [:index]

  def index
    if params[:location_id]
      @todays_events = Location.by_user(current_user).find(params[:location_id]).events.starts_today
      @upcoming_events = Location.by_user(current_user).find(params[:location_id]).events.upcoming_events
      @old_events = Location.by_user(current_user).find(params[:location_id]).events.old_events
    elsif params[:participant_id]
      @todays_events = Participant.by_user(current_user).find(params[:participant_id]).events.starts_today
      @upcoming_events = Participant.by_user(current_user).find(params[:participant_id]).events.upcoming_events
      @old_events = Participant.by_user(current_user).find(params[:participant_id]).events.old_events
    else
      @todays_events = Event.by_user(current_user).starts_today
      @upcoming_events = Event.by_user(current_user).upcoming_events
      @old_events = Event.by_user(current_user).old_events
    end

    if request.xhr? != 0
      render "index"
    else
      render json: @location.events if @location
      render json: @participant.events if @participant
    end
  end

  def create
    create_params = events_param
    create_params[:user_id] = session[:user_id]
    @event = Event.new(create_params)
    if @event.save
      redirect_to @location ? location_events_path : events_path
    else
      render :new
    end
  end

  def new
    @event = Event.new(location_id: params[:location_id]) if params[:location_id]
  end

  def show
  end

  def update
    if @event.update(events_param)
      redirect_to @location ? location_event_path(@location) : event_path(@event), notice: "Event was updated successfully!"
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path, notice: "Event was deleted successfully."
  end

  private
    def set_location
      @location = Location.by_user(current_user).find(params[:location_id]) if params[:location_id]
    end

    def set_participant
      @participant = Participant.by_user(current_user).find(params[:participant_id]) if params[:participant_id]
    end

    def set_event
      @event = Event.by_user(current_user).find(params[:id])
    end

    def create_event
      @event = current_user.events.build
    end

    def events_param
      params.require(:event).permit(:name, :start_time, :end_time, :location_id, participant_ids: [], location_attributes: [:name], participants_attributes: [:nickname])
    end
end

app/helpers/events_helper.rb
module EventsHelper
  def formatted_time(time)
    time.localtime.strftime("%B %e, %Y - %l:%M %p (%Z)")
  end

  def event_to_s(event)
    "#{event.name} (#{formatted_time(event.start_time)} ~ #{formatted_time(event.end_time)})"
  end
end

app/views/events/_events.html.erb
<table class="event_table">
  <tr>
    <th>Event Name</th>
    <th>Start Time</th>
    <th>End Time</th>
    <th>Participants</th>
  </tr>
  <% events.each do |event| %>
    <tr>
      <% if location %>
        <td><%= link_to event.name, location_event_path(location, event) %></td>
      <% else %>
        <td><%= link_to event.name, event_path(event) %></td>
      <% end %>
      <td><%= formatted_time(event.start_time) %></td>
      <td><%= formatted_time(event.end_time) %></td>
      <td><%= event.participants.count %>
    </tr>
  <% end %>
</table>

app/views/events/_form.html.erb
<%= render "layouts/form_errors", object: event %>

<% if @location %>
  <%= form_for event, url: event.id ? "/locations/#{@location.id}/events/#{event.id}" :"/locations/#{@location.id}/events" do |f| %>
    <%= render "form_details", {f: f, location: @location, event: event } %>
  <% end %>
<% else %>
  <%= form_for event do |f| %>
    <%= render "form_details", {f: f, event: event } %>
  <% end %>
<% end %>

app/views/events/_form_details.erb
<fieldset class="event_fieldset">
    <%= f.hidden_field :location_id if @location %>
    <h3>Event Details</h3>
    <div>
      <%= f.label :name, "Name"%><br>
      <%= f.text_field :name, class: "shadow" %>
    </div>
    <br>
    <div>
      <%= f.label :start_time, "Start Time"%><br>
      <%= f.datetime_field :start_time, ampm: true, class: "shadow" %>
    </div>
    <br>
    <div>
      <%= f.label :end_time, "End Time"%><br>
      <%= f.datetime_field :end_time, ampm: true, class: "shadow" %>
    </div>
    <br>
    
    <% if !@location %>
      <h3>Location for this event</h3>
      <% if current_user.locations.any? %>
        <div>
          <%= f.label :location, "Choose an existing location: " %>
          <%= f.collection_select :location_id, current_user.locations, :id, :name, include_blank: true %>
          <p>OR</p>
        </div>
      <% end %>

      <%= f.fields_for :location, event.build_location do |location| %>
        <%= location.label :name, "Create a new location by entering a new name: " %>
        <%= location.text_field :name, class: "shadow" %>
      <% end %>
    <% else %>
      <h3><%= "Location: #{@location.name}" %></h3>
    <% end %>

    

    <h3>Participants for this event</h3>
    <p>You may also choose to add participants later</p>
    <% if current_user.participants.any? %>
      <div>
        <%= f.label :location, "Choose (an) existing participant(s): " %><br>
        <%= f.collection_check_boxes :participant_ids, current_user.participants, :id, :nickname %>
        <p>OR</p>
      </div>
    <% end %>

    <p>Create up to 25 new participants</p>
    <ol>
    <% 25.times do %>
      <%= f.fields_for :participants, event.participants.build do |participant| %>
        <li>
        <%= participant.text_field :nickname, placeholder: "Nickname", class: "shadow" %></li>
      <% end %>
    <% end %>
    </ol>
    <div>
      <%= f.submit %>
    </div>
  </fieldset>

app/views/events/edit.html.erb
<div class="edit_event">
  <h1>Edit <%= @event.name %></h1>
  <%= render 'form', event: @event %>
</div>

app/views/events/index.html.erb
<div class="events_index">

  <% if @location %>
    <h1>Events at <%= @location.name %></h1>
  <% elsif @participant %>
    <h1>Events for <%= participant_to_s(@participant) %></h1>
  <% else %>
    <h1>Events</h1>
  <% end %>

  <% if !@location %>
    <p><%= link_to "+ Add a New Event", new_event_path, class: "add_event" %></p>
  <% else %>
    <p><%= link_to "+ Add a New Event for #{@location.name}", new_location_event_path, class: "add_event" %></p>
  <% end %>

  <% if !@todays_events.empty? %>
    <h2>Today's Events</h2>

    <%= render "events", { events: @todays_events, location: @location } %>
  <% end %>  

  <% if !@upcoming_events.empty? %>
    <h2>Upcoming Events</h2>

    <%= render "events", { events: @upcoming_events, location: @location } %>
  <% end %>

  <% if !@old_events.empty? %>
    <h2>Past Events</h2>

    <%= render "events", { events: @old_events, location: @location } %>
  <% end %>
</div>

app/views/events/new.html.erb
<div class="new_event">
  <h1>Create A New Event</h1>
  <%= render 'form', event: @event %>
</div>

app/views/events/show.html.erb
<h1 id="main_head"><%= "#{@location.name}'s" if @location %> Event Details -
  <%= link_to "edit", @location ? edit_location_event_path(@location) : edit_event_path(@event) %> |
  <%= link_to "delete", event_path(@event), method: :delete, data: { confirm: "Are you sure?"} %>
</h1>

<div class="event_details">
  <h3>Name: <%= @event.name %></h3>
  <h3>Start Time: <%= formatted_time(@event.start_time) %></h3>
  <h3>End Time: <%= formatted_time(@event.end_time) %></h3>
</div>

<% if !@location %>
  <div class="event_location">
    <h1>Location</h1>
    <h3>Name: <%= link_to @event.location.name, location_path(@event.location) %></h3>
  </div>
<% end %>

<% if @event.participants.any? %>
  <div class="event_participants">
    <h1>Participants</h1>
    <%= link_to "Load Participants", event_participants_path(@event), class: "load_participants" %>
    <div class="participants"> 
    </div>
  <% else %>
    <h1>No participants for this event</h1>
  </div>
<% end %>