config/routes.rb
Rails.application.routes.draw do
  resources :events

  resources :locations do
    resources :events
  end

  resources :participants do
    resources :events
  end

  resources :locations do
    resources :events, only: :index
  end

  resources :events do
    resources :participants, only: :index
  end


  get 'welcome/home'
  root 'welcome#home'

  get '/signin' => "sessions#signin"
  post '/signin' => 'sessions#signin_post', as: "signin_post"
  get '/signup' => 'sessions#signup'
  post '/signup' => 'sessions#signup_post', as: "signup_post"
  delete "/signout" => 'sessions#signout'

  get '/auth/facebook/callback' => 'sessions#facebook'
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user
  has_many :events, dependent: :destroy  
  has_many :participants, through: :events

  validates :name, presence: true
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :redirect_if_not_signed_in
  before_action :create_location, only: [:index, :new]
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  before_action :set_locations, only: [:index]

  def create
    @location = current_user.locations.build(location_params)

    if @location.save
      respond_to do |f|
        f.html { redirect_to locations_path, notice: "Location was created successfully" }
        f.json { render json: @location}
      end
    else
      render :new
    end
  end

  def show
    set_previous_location(@location)
    set_next_location(@location)
    set_location_indexes(@location)
    if request.xhr? != 0
      render "show"
    else
      render json: @location
    end
  end

  def update
    if @location.update(location_params)
      redirect_to location_path(@location), notice: "Location was updated successfully"
    else
      render :edit
    end
  end

  def destroy
    @location.destroy
    redirect_to locations_path, notice: "Location and all its associated events are deleted successfully"
  end

  private
    def set_previous_location(location)
      @previous = Location.previous(location)
    end

    def set_next_location(location)
      @next = Location.next(location)
    end

    def set_location_indexes(location)
      @indexes = Location.indexes(location)
    end

    def set_locations
      @locations = Location.by_user(current_user)
    end

    def create_location
      @location = current_user.locations.build
    end

    def set_location
      @location = Location.by_user(current_user).find(params[:id])
    end

    def location_params
      params.require(:location).permit(:name, :street_address, :city, :state, :zipcode)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
  def location_to_s(location)
    "#{location.name}"
  end
end

app/views/locations/_form.html.erb
<%= render "layouts/form_errors", object: location %>

<%= form_for location do |f| %>
  <fieldset class="participant_fieldset">
    <h3>Location Details</h3>
    <div>
      <%= f.label :name, "Name"%><br>
      <%= f.text_field :name, class: "shadow" %>
    </div>
    <br>

    <div>
      <%= f.label :street_address, "Street Address"%><br>
      <%= f.text_field :street_address, class: "shadow" %>
    </div>
    <br>
  
    <div>
      <%= f.label :city, "City"%><br>
      <%= f.text_field :city, class: "shadow" %>
    </div>
    <br>

    <div>
      <%= f.label :state, "State"%><br>
      <%= f.text_field :state, class: "shadow" %>
    </div>
    <br>

    <div>
      <%= f.label :zipcode, "Zipcode"%><br>
      <%= f.text_field :zipcode, class: "shadow" %>
    </div>
    <br>

    <div>
      <%= f.submit %>
    </div>
  </fieldset>
<% end %>

app/views/locations/_locations.html.erb
<table class="location_table">
  <tr>
    <th>Name</th>
    <th>Street Adress</th>
    <th>City</th>
    <th>State</th>
    <th>Zipcode</th>
    <th>Events</th>
  </tr>
  <% locations.each do |location| %>
    <tr>
      <td><%= link_to location.name, location_path(location) %></td>
      <td><%= location.street_address %></td>
      <td><%= location.city %></td>
      <td><%= location.state %></td>
      <td><%= location.zipcode %></td>
      <td><%= link_to location.events.count, location_events_path(location) %>
    </tr>
  <% end %>
</table>

app/views/locations/edit.html.erb
<div class="edit_location">
  <h1>Edit <%= @location.name %></h1>
  <%= render 'form', location: @location %>
</div>

app/views/locations/index.html.erb
<div class="locations_index">
  <h1>Locations</h1>
  <p><%= link_to "+ New Location", new_location_path, class: "add_location shadow" %></p>

  <div class="quick_location shadow">
    <p>OR quickly create a new location</p>

    <%= form_for @location do |f| %>
      <div>
        <%= f.label :name, "Location Name"%><br>
        <%= f.text_field :name %>     
      </div>

      <div>
        <%= f.submit %>
      </div>
    <% end %>
  </div>
  <br>

  <% if !@locations.empty? %>
    <%= render "locations", locations: @locations %>
  <% end %>  
</div>

app/views/locations/new.html.erb
<div class="new_location">
  <h1>Create A New Location</h1>
  <%= render 'form', location: @location %>
</div>

app/views/locations/show.html.erb
<h1 id="main_head">Location Details -
  <%= link_to "edit", edit_location_path(@location) %> |
  <%= link_to "delete", location_path(@location), method: :delete, data: { confirm: "Are you sure?  WARNING: This will also destroy all events that are associated with this location."} %>
</h1>

<div class="location_details shadow">
  <%= link_to "<", location_path(@previous), class: "load_previous_location", data: {indexes: @indexes, current: @location.id} %>
  <%= link_to ">", location_path(@next), class: "load_next_location", data: {indexes: @indexes, current: @location.id} %>

  <h3 id="name">Name: <%= @location.name %></h3>
  <h3 id="street_address">Street Address: <%= @location.street_address %></h3>
  <h3 id="city">City: <%= @location.city %></h3>
  <h3 id="state">State: <%= @location.state %></h3>
  <h3 id="zipcode">Zipcode: <%= @location.zipcode %></h3>
</div>

<div class="location_events">
  <% if @location.events.any? %>
    <h1>Events</h1>
    <%= link_to "Load Events", location_events_path(@location), class: "load_location_events" %>
    <div class="events"> 
    </div>
  <% else %>
    <h1>No events at this location</h1>
  <% end %>
</div>