config/routes.rb
Rails.application.routes.draw do
  resources :events

  resources :locations do
    resources :events
  end

  resources :participants do
    resources :events
  end

  resources :locations do
    resources :events, only: :index
  end

  resources :events do
    resources :participants, only: :index
  end


  get 'welcome/home'
  root 'welcome#home'

  get '/signin' => "sessions#signin"
  post '/signin' => 'sessions#signin_post', as: "signin_post"
  get '/signup' => 'sessions#signup'
  post '/signup' => 'sessions#signup_post', as: "signup_post"
  delete "/signout" => 'sessions#signout'

  get '/auth/facebook/callback' => 'sessions#facebook'
end

app/views/layouts/_back.html.erb
<br><br><%= link_to "Go Back", url_for(:back), {class: "go_back"} %>

app/views/layouts/_errors.html.erb
  <%= content_tag(:div, flash[:error], id: "flash_error", class: "container") if flash[:error] %> 
  <%= content_tag(:div, flash[:notice], id: "flash_notice", class: "container") if flash[:notice] %> 
  <%= content_tag(:div, flash[:alert], id: "flash_alert", class: "container") if flash[:alert] %>

app/views/layouts/_form_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2>Please fix: <%= pluralize(object.errors.count, "error") %> on this form </h2>
    
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav>
  <ul>
    <% if signed_in? %>
      <li class="nav_events"><%= link_to "Events", events_path %></li>
      <li class="nav_participants"><%= link_to "Participants", participants_path %></li>
      <li class="nav_locations"><%= link_to "Locations", locations_path %></li>
      <li class="nav_signout"><%= link_to "Sign Out", signout_path, method: :delete %></li>
    <% else %>
      <li class="nav_home"><%= link_to "Home", root_path %></li>
      <li class="nav_signup"><%= link_to "Sign Up", signup_path %></li>
      <li class="nav_signin"><%= link_to "Sign In", signin_path %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "layouts/navigation" %>
    <%= render "layouts/errors" %>
    
    <div class="main">
      <%= yield %>
      <%= render "layouts/back" %>
    </div>
  </body>
</html>